In [1]:
import pandas as pd

In [2]:
df = pd.read_csv('03-01-2025 BIANCA KELLY DE SOUZA PULTZ.csv', sep=';')
df

,AT ID,Sequence,Stop,SPX TN,Destination Address,Bairro,City,Zipcode/Postal code,Latitude,Longitude
0,AT2025010300T4A,1,1,BR248065007244L,"Rua Doutor Raul Schwinden, 283",Jardim Empyreo,Leme,13611-821,"-22,2072368","-47,3752879"
1,AT2025010300T4A,2,2,BR2415833943939,"Rua Waldemar de Souza, 395, Perto casa de ração",Jardim Empyreo,Leme,13611-820,"-22,2080695","-47,376612"
2,AT2025010300T4A,3,2,BR247117822685E,"Rua Waldemar de Souza, 395, Perto casa de ração",Jardim Empyreo,Leme,13611-820,"-22,2080695","-47,376612"
3,AT2025010300T4A,4,3,BR246006302425R,"Rua Wagner Ouro Preto, 326",Jardim Empyreo,Leme,13611-823,"-22,2081088","-47,3745955"
4,AT2025010300T4A,5,4,BR248162609312E,"Avenida Cicera Sueli de Andrade, 140",Jardim Empyreo,Leme,13611-831,"-22,2067609","-47,3739584"
...,...,...,...,...,...,...,...,...,...,...
79,AT2025010300T4A,82,43,BR2453581131519,"Rua Wagner Ouro Preto, 55",Jardim Empyreo,Leme,13611-823,"-22,204422","-47,3721851"
80,AT2025010300T4A,83,43,BR2433815518559,"Rua Wagner Ouro Preto, 55",Jardim Empyreo,Leme,13611-823,"-22,204422","-47,3721851"
81,AT2025010300T4A,84,44,BR244766355365P,"Rua Wagner Ouro Preto, 231",Jardim Empyreo,Leme,13611-823,"-22,2045196","-47,3725068"
82,AT2025010300T4A,85,44,BR249871563590P,"Rua Wagner Ouro Preto, 237, Perto do mineiro l...",Jardim Empyreo,Leme,13611-823,"-22,2045536","-47,3725293"
83,AT2025010300T4A,86,44,BR249649175559B,"Rua Wagner Ouro Preto, 237, Perto do mineiro l...",Jardim Empyreo,Leme,13611-823,"-22,2045536","-47,3725293"

In [3]:
df.columns = df.columns.str.lower().str.replace(' ', '_')

str_columns = list(df.dtypes[df.dtypes == 'object'].index)

for col in str_columns:
    df[col] = df[col].str.lower().str.replace(' ', '_')

In [4]:
df

,at_id,sequence,stop,spx_tn,destination_address,bairro,city,zipcode/postal_code,latitude,longitude
0,at2025010300t4a,1,1,br248065007244l,"rua_doutor_raul_schwinden,_283",jardim_empyreo,leme,13611-821,"-22,2072368","-47,3752879"
1,at2025010300t4a,2,2,br2415833943939,"rua_waldemar_de_souza,_395,_perto_casa_de_ração",jardim_empyreo,leme,13611-820,"-22,2080695","-47,376612"
2,at2025010300t4a,3,2,br247117822685e,"rua_waldemar_de_souza,_395,_perto_casa_de_ração",jardim_empyreo,leme,13611-820,"-22,2080695","-47,376612"
3,at2025010300t4a,4,3,br246006302425r,"rua_wagner_ouro_preto,_326",jardim_empyreo,leme,13611-823,"-22,2081088","-47,3745955"
4,at2025010300t4a,5,4,br248162609312e,"avenida_cicera_sueli_de_andrade,_140",jardim_empyreo,leme,13611-831,"-22,2067609","-47,3739584"
...,...,...,...,...,...,...,...,...,...,...
79,at2025010300t4a,82,43,br2453581131519,"rua_wagner_ouro_preto,_55",jardim_empyreo,leme,13611-823,"-22,204422","-47,3721851"
80,at2025010300t4a,83,43,br2433815518559,"rua_wagner_ouro_preto,_55",jardim_empyreo,leme,13611-823,"-22,204422","-47,3721851"
81,at2025010300t4a,84,44,br244766355365p,"rua_wagner_ouro_preto,_231",jardim_empyreo,leme,13611-823,"-22,2045196","-47,3725068"
82,at2025010300t4a,85,44,br249871563590p,"rua_wagner_ouro_preto,_237,_perto_do_mineiro_l...",jardim_empyreo,leme,13611-823,"-22,2045536","-47,3725293"
83,at2025010300t4a,86,44,br249649175559b,"rua_wagner_ouro_preto,_237,_perto_do_mineiro_l...",jardim_empyreo,leme,13611-823,"-22,2045536","-47,3725293"

In [5]:
df.destination_address.value_counts()

destination_address
rua_professor_antonio_roversi,_424                                           7
rua_reginaldo_amorim_dos_santos,_71                                          3
rua_constantino_parolin,_794                                                 3
rua_reginaldo_amorim_dos_santos,_31,_casa                                    3
avenida_sebastião_rodrigues_de_lara,_1045,_casa_em_frente_o_restaurante_a    2
                                                                            ..
rua_professor_antonio_roversi,_565,_casa                                     1
avenida_sebastião_rodrigues_de_lara,_313,_casa                               1
rua_abilio_zanca,_1176                                                       1
rua_wagner_ouro_preto,_74                                                    1
rua_wagner_ouro_preto,_231                                                   1
Name: count, Length: 63, dtype: int64

In [25]:
def combine_packages(series):
    return ', '.join(series)

In [37]:
df['packages'] = df.groupby('destination_address')['spx_tn'].transform(combine_packages)
print(df[['destination_address', 'packages']])

                                  destination_address  \
0                      rua_doutor_raul_schwinden,_283
1     rua_waldemar_de_souza,_395,_perto_casa_de_ração
2     rua_waldemar_de_souza,_395,_perto_casa_de_ração
3                          rua_wagner_ouro_preto,_326
4                avenida_cicera_sueli_de_andrade,_140
..                                                ...
79                          rua_wagner_ouro_preto,_55
80                          rua_wagner_ouro_preto,_55
81                         rua_wagner_ouro_preto,_231
82  rua_wagner_ouro_preto,_237,_perto_do_mineiro_l...
83  rua_wagner_ouro_preto,_237,_perto_do_mineiro_l...

                            packages
0                    br248065007244l
1   br2415833943939, br247117822685e
2   br2415833943939, br247117822685e
3                    br246006302425r
4                    br248162609312e
..                               ...
79  br2453581131519, br2433815518559
80  br2453581131519, br2433815518559
81                   br244766355365p
82  br249871563590p, br249649175559b
83  br249871563590p, br249649175559b

[84 rows x 2 columns]

In [44]:
df_routes = df[['destination_address', 'packages']].drop_duplicates()
print(df_routes)

                                  destination_address  \
0                      rua_doutor_raul_schwinden,_283
1     rua_waldemar_de_souza,_395,_perto_casa_de_ração
3                          rua_wagner_ouro_preto,_326
4                avenida_cicera_sueli_de_andrade,_140
5              avenida_sebastião_rodrigues_de_lara,_9
..                                                ...
77     avenida_sebastião_rodrigues_de_lara,_313,_casa
78                          rua_wagner_ouro_preto,_74
79                          rua_wagner_ouro_preto,_55
81                         rua_wagner_ouro_preto,_231
82  rua_wagner_ouro_preto,_237,_perto_do_mineiro_l...

                            packages
0                    br248065007244l
1   br2415833943939, br247117822685e
3                    br246006302425r
4                    br248162609312e
5                    br240003798892d
..                               ...
77                   br242883557633s
78                   br241013604930q
79  br2453581131519, br2433815518559
81                   br244766355365p
82  br249871563590p, br249649175559b

[63 rows x 2 columns]

In [60]:
df[['destination_address', 'packages']].drop_duplicates().to_csv('df_routes.xlsx', index=False, encoding='utf-8', sep=';')

In [50]:
df

,at_id,sequence,stop,spx_tn,destination_address,bairro,city,zipcode/postal_code,latitude,longitude,packages
0,at2025010300t4a,1,1,br248065007244l,"rua_doutor_raul_schwinden,_283",jardim_empyreo,leme,13611-821,"-22,2072368","-47,3752879",br248065007244l
1,at2025010300t4a,2,2,br2415833943939,"rua_waldemar_de_souza,_395,_perto_casa_de_ração",jardim_empyreo,leme,13611-820,"-22,2080695","-47,376612","br2415833943939, br247117822685e"
2,at2025010300t4a,3,2,br247117822685e,"rua_waldemar_de_souza,_395,_perto_casa_de_ração",jardim_empyreo,leme,13611-820,"-22,2080695","-47,376612","br2415833943939, br247117822685e"
3,at2025010300t4a,4,3,br246006302425r,"rua_wagner_ouro_preto,_326",jardim_empyreo,leme,13611-823,"-22,2081088","-47,3745955",br246006302425r
4,at2025010300t4a,5,4,br248162609312e,"avenida_cicera_sueli_de_andrade,_140",jardim_empyreo,leme,13611-831,"-22,2067609","-47,3739584",br248162609312e
...,...,...,...,...,...,...,...,...,...,...,...
79,at2025010300t4a,82,43,br2453581131519,"rua_wagner_ouro_preto,_55",jardim_empyreo,leme,13611-823,"-22,204422","-47,3721851","br2453581131519, br2433815518559"
80,at2025010300t4a,83,43,br2433815518559,"rua_wagner_ouro_preto,_55",jardim_empyreo,leme,13611-823,"-22,204422","-47,3721851","br2453581131519, br2433815518559"
81,at2025010300t4a,84,44,br244766355365p,"rua_wagner_ouro_preto,_231",jardim_empyreo,leme,13611-823,"-22,2045196","-47,3725068",br244766355365p
82,at2025010300t4a,85,44,br249871563590p,"rua_wagner_ouro_preto,_237,_perto_do_mineiro_l...",jardim_empyreo,leme,13611-823,"-22,2045536","-47,3725293","br249871563590p, br249649175559b"
83,at2025010300t4a,86,44,br249649175559b,"rua_wagner_ouro_preto,_237,_perto_do_mineiro_l...",jardim_empyreo,leme,13611-823,"-22,2045536","-47,3725293","br249871563590p, br249649175559b"